/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Taras' at '5/9/17 10:13 PM' with Gradle 2.14.1
 *
 * @author Taras, @date 5/9/17 10:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
